AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: Fitness
Resources:
  Fitness:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: main.lambda_handler
      Runtime: python3.13
      MemorySize: 1024
      EphemeralStorage:
        Size: 512
      Timeout: 150
      Architectures:
        - x86_64
